create table "public"."likes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "user_id" uuid not null,
    "tweet_id" uuid not null
);


alter table "public"."likes" enable row level security;

CREATE UNIQUE INDEX likes_pkey ON public.likes USING btree (id);

alter table "public"."likes" add constraint "likes_pkey" PRIMARY KEY using index "likes_pkey";

alter table "public"."likes" add constraint "likes_tweet_id_fkey" FOREIGN KEY (tweet_id) REFERENCES tweets(id) ON DELETE CASCADE not valid;

alter table "public"."likes" validate constraint "likes_tweet_id_fkey";

alter table "public"."likes" add constraint "likes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."likes" validate constraint "likes_user_id_fkey";

create policy "anyone can select likes"
on "public"."likes"
as permissive
for select
to public
using (true);


create policy "authenticated user can like tweet"
on "public"."likes"
as permissive
for insert
to authenticated
with check ((user_id = auth.uid()));


create policy "authenticated users can delete their likes"
on "public"."likes"
as permissive
for delete
to authenticated
using ((user_id = auth.uid()));



